[
  {
    authorName: "Test Member",
    authorEmail: "testmember@gmail.com",
    authorRole: "Member",
    authorId: "680c559d110db4d98289de91",
    postTitle: "Why Daily Cardio Boosts Your Heart Health",
    postContent:
      "Strength training is more than just muscle—it helps metabolism and bone health too.",
    tags: ["strength", "fitness", "health", "training", "wellness"],
    createdAt: "Jun 11 2025 08:45:00",
    liked: ["user@gmail.com", "testtrainer@gmail.com"],
    disliked: ["johnny.sins@example.com"],
    comments: [
      {
        user: "Johnny Sins",
        role: "Trainer",
        userImg:
          "https://i.ibb.co/Ngzny0ch/trainer2-gmail-com-profile-image.jpg",
        time: "Jun 11 2025 09:15:00",
        content: "This is a helpful post about wellness.",
        liked: ["testmember@gmail.com"],
        disliked: [],
      },
      {
        user: "Farzad sami",
        role: "Member",
        userImg: "https://i.ibb.co/8LH7MRm1/blob.jpg",
        time: "Jun 11 2025 09:15:00",
        content: "This is a helpful post about wellness.",
        liked: [],
        disliked: ["psazzadul@gmail.com"],
      },
      {
        user: "Test Trainer",
        role: "Trainer",
        userImg:
          "https://i.ibb.co/DDGzhsRZ/trainertest-gmail-com-profile-image.jpg",
        time: "Jun 11 2025 09:15:00",
        content: "This is a helpful post about wellness.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Sazzadul Islam Molla",
    authorEmail: "user@gmail.com",
    authorRole: "Member",
    authorId: "67765beb8b7940eac4ca2c55",
    postTitle: "Flexibility Tips for Beginners",
    postContent:
      "Yoga calms the mind and loosens tight muscles for daily relief.",
    tags: ["yoga", "flexibility", "stress relief", "wellness", "mindfulness"],
    createdAt: "Jun 11 2025 06:45:00",
    liked: ["psazzadul1205@gmail.com", "johnny.sins@example.com"],
    disliked: ["testmember@gmail.com"],
    comments: [
      {
        user: "Thomas King",
        role: "Trainer",
        userImg: "https://i.ibb.co.com/SwkPVWtN/cropped-image.jpg",
        time: "Jun 11 2025 07:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: ["user@gmail.com"],
        disliked: [],
      },
      {
        user: "Farzad sami",
        role: "Member",
        userImg: "https://i.ibb.co/8LH7MRm1/blob.jpg",
        time: "Jun 11 2025 07:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: [],
        disliked: ["johnny.sins@example.com"],
      },
      {
        user: "Test Trainer",
        role: "Trainer",
        userImg:
          "https://i.ibb.co/DDGzhsRZ/trainertest-gmail-com-profile-image.jpg",
        time: "Jun 11 2025 07:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Muntaha",
    authorEmail: "psazzadul1205@gmail.com",
    authorRole: "Member",
    authorId: "67ee146fe6b73282444ab248",
    postTitle: "How Strength Training Transforms Your Body",
    postContent: "Balanced nutrition fuels performance and promotes recovery.",
    tags: ["nutrition", "diet", "energy", "lifestyle", "balance"],
    createdAt: "Jun 11 2025 04:45:00",
    liked: ["testmember@gmail.com", "testtrainer@gmail.com"],
    disliked: ["user@gmail.com"],
    comments: [
      {
        user: "Test Trainer",
        role: "Trainer",
        userImg:
          "https://i.ibb.co/DDGzhsRZ/trainertest-gmail-com-profile-image.jpg",
        time: "Jun 11 2025 05:15:00",
        content: "This is a helpful post about balance.",
        liked: ["psazzadul1205@gmail.com"],
        disliked: [],
      },
      {
        user: "Farzad sami",
        role: "Member",
        userImg: "https://i.ibb.co/8LH7MRm1/blob.jpg",
        time: "Jun 11 2025 05:15:00",
        content: "This is a helpful post about balance.",
        liked: [],
        disliked: ["testmember@gmail.com"],
      },
      {
        user: "Johnny Sins",
        role: "Trainer",
        userImg:
          "https://i.ibb.co/Ngzny0ch/trainer2-gmail-com-profile-image.jpg",
        time: "Jun 11 2025 05:15:00",
        content: "This is a helpful post about balance.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Test Trainer",
    authorEmail: "testtrainer@gmail.com",
    authorRole: "Member",
    authorId: "680b199b2aa069057458d392",
    postTitle: "The Connection Between Diet and Performance",
    postContent: "Consistency in cardio improves heart rate and lowers stress.",
    tags: ["cardio", "heart", "endurance", "routine", "running"],
    createdAt: "Jun 11 2025 02:45:00",
    liked: ["johnny.sins@example.com", "psazzadul1205@gmail.com"],
    disliked: ["testtrainer@gmail.com"],
    comments: [
      {
        user: "Test Member",
        role: "Member",
        userImg: "https://i.ibb.co.com/ynmjwSHZ/blob.jpg",
        time: "Jun 11 2025 03:15:00",
        content: "This is a helpful post about running.",
        liked: ["testtrainer@gmail.com"],
        disliked: [],
      },
      {
        user: "Farzad sami",
        role: "Member",
        userImg: "https://i.ibb.co/8LH7MRm1/blob.jpg",
        time: "Jun 11 2025 03:15:00",
        content: "This is a helpful post about running.",
        liked: [],
        disliked: ["psazzadul1205@gmail.com"],
      },
      {
        user: "Thomas King",
        role: "Trainer",
        userImg: "https://i.ibb.co.com/SwkPVWtN/cropped-image.jpg",
        time: "Jun 11 2025 03:15:00",
        content: "This is a helpful post about running.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Johnny Sins",
    authorEmail: "johnny.sins@example.com",
    authorRole: "Trainer",
    authorId: "68353156b613825c3f5136c3",
    postTitle: "Mindfulness Techniques for Gym-goers",
    postContent:
      "Flexibility training boosts range of motion and prevents injuries.",
    tags: ["yoga", "flexibility", "stress relief", "wellness", "mindfulness"],
    createdAt: "Jun 11 2025 00:45:00",
    liked: ["user@gmail.com", "testmember@gmail.com"],
    disliked: ["testtrainer@gmail.com"],
    comments: [
      {
        user: "Test Member",
        role: "Member",
        userImg: "https://i.ibb.co.com/ynmjwSHZ/blob.jpg",
        time: "Jun 11 2025 01:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: ["johnny.sins@example.com"],
        disliked: [],
      },
      {
        user: "Muntaha",
        role: "Member",
        userImg: "https://i.ibb.co.com/gLgKcvwv/blob.jpg",
        time: "Jun 11 2025 01:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: [],
        disliked: ["user@gmail.com"],
      },
      {
        user: "Thomas King",
        role: "Trainer",
        userImg: "https://i.ibb.co.com/SwkPVWtN/cropped-image.jpg",
        time: "Jun 11 2025 01:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Farzad sami",
    authorEmail: "psazzadul@gmail.com",
    authorRole: "Member",
    authorId: "6814414d68c39017f7676e3a",
    postTitle: "Yoga or Cardio: What Should You Choose?",
    postContent:
      "Strength training is more than just muscle—it helps metabolism and bone health too.",
    tags: ["strength", "fitness", "health", "training", "wellness"],
    createdAt: "Jun 10 2025 22:45:00",
    liked: ["testmember@gmail.com", "user@gmail.com"],
    disliked: ["johnny.sins@example.com"],
    comments: [
      {
        user: "Muntaha",
        role: "Member",
        userImg: "https://i.ibb.co.com/gLgKcvwv/blob.jpg",
        time: "Jun 10 2025 23:15:00",
        content: "This is a helpful post about wellness.",
        liked: ["psazzadul@gmail.com"],
        disliked: [],
      },
      {
        user: "Test Trainer",
        role: "Trainer",
        userImg:
          "https://i.ibb.co/DDGzhsRZ/trainertest-gmail-com-profile-image.jpg",
        time: "Jun 10 2025 23:15:00",
        content: "This is a helpful post about wellness.",
        liked: [],
        disliked: ["user@gmail.com"],
      },
      {
        user: "Thomas King",
        role: "Trainer",
        userImg: "https://i.ibb.co.com/SwkPVWtN/cropped-image.jpg",
        time: "Jun 10 2025 23:15:00",
        content: "This is a helpful post about wellness.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Test Member",
    authorEmail: "testmember@gmail.com",
    authorRole: "Member",
    authorId: "680c559d110db4d98289de91",
    postTitle: "Simple Home Workouts That Work Wonders",
    postContent: "Balanced nutrition fuels performance and promotes recovery.",
    tags: ["nutrition", "diet", "energy", "lifestyle", "balance"],
    createdAt: "Jun 10 2025 20:45:00",
    liked: ["testtrainer@gmail.com", "psazzadul@gmail.com"],
    disliked: ["user@gmail.com"],
    comments: [
      {
        user: "Farzad sami",
        role: "Member",
        userImg: "https://i.ibb.co/8LH7MRm1/blob.jpg",
        time: "Jun 10 2025 21:15:00",
        content: "This is a helpful post about balance.",
        liked: ["testmember@gmail.com"],
        disliked: [],
      },
      {
        user: "Sazzadul Islam Molla",
        role: "Member",
        userImg: "https://i.ibb.co.com/PZpnHdqC/cropped-avatar.jpg",
        time: "Jun 10 2025 21:15:00",
        content: "This is a helpful post about balance.",
        liked: [],
        disliked: ["psazzadul@gmail.com"],
      },
      {
        user: "Thomas King",
        role: "Trainer",
        userImg: "https://i.ibb.co.com/SwkPVWtN/cropped-image.jpg",
        time: "Jun 10 2025 21:15:00",
        content: "This is a helpful post about balance.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Thomas King",
    authorEmail: "thomas.king@example.com",
    authorRole: "Trainer",
    authorId: "676e9791205adb04706021d6",
    postTitle: "Meal Planning for Active Lifestyles",
    postContent: "Consistency in cardio improves heart rate and lowers stress.",
    tags: ["cardio", "heart", "endurance", "routine", "running"],
    createdAt: "Jun 10 2025 18:45:00",
    liked: ["user@gmail.com", "johnny.sins@example.com"],
    disliked: ["testmember@gmail.com"],
    comments: [
      {
        user: "Muntaha",
        role: "Member",
        userImg: "https://i.ibb.co.com/gLgKcvwv/blob.jpg",
        time: "Jun 10 2025 19:15:00",
        content: "This is a helpful post about running.",
        liked: ["thomas.king@example.com"],
        disliked: [],
      },
      {
        user: "Farzad sami",
        role: "Member",
        userImg: "https://i.ibb.co/8LH7MRm1/blob.jpg",
        time: "Jun 10 2025 19:15:00",
        content: "This is a helpful post about running.",
        liked: [],
        disliked: ["user@gmail.com"],
      },
      {
        user: "Test Trainer",
        role: "Trainer",
        userImg:
          "https://i.ibb.co/DDGzhsRZ/trainertest-gmail-com-profile-image.jpg",
        time: "Jun 10 2025 19:15:00",
        content: "This is a helpful post about running.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Test Trainer",
    authorEmail: "trainertest@gmail.com",
    authorRole: "Trainer",
    authorId: "6842ac1153a96ee6195fe6c0",
    postTitle: "The Power of Recovery Days in Training",
    postContent:
      "Flexibility training boosts range of motion and prevents injuries.",
    tags: ["yoga", "flexibility", "stress relief", "wellness", "mindfulness"],
    createdAt: "Jun 10 2025 16:45:00",
    liked: ["johnny.sins@example.com", "psazzadul@gmail.com"],
    disliked: ["testtrainer@gmail.com"],
    comments: [
      {
        user: "Test Member",
        role: "Member",
        userImg: "https://i.ibb.co.com/ynmjwSHZ/blob.jpg",
        time: "Jun 10 2025 17:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: ["trainertest@gmail.com"],
        disliked: [],
      },
      {
        user: "Sazzadul Islam Molla",
        role: "Member",
        userImg: "https://i.ibb.co.com/PZpnHdqC/cropped-avatar.jpg",
        time: "Jun 10 2025 17:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: [],
        disliked: ["johnny.sins@example.com"],
      },
      {
        user: "Thomas King",
        role: "Trainer",
        userImg: "https://i.ibb.co.com/SwkPVWtN/cropped-image.jpg",
        time: "Jun 10 2025 17:15:00",
        content: "This is a helpful post about mindfulness.",
        liked: [],
        disliked: [],
      },
    ],
  },
  {
    authorName: "Sazzadul Islam Molla",
    authorEmail: "user@gmail.com",
    authorRole: "Member",
    authorId: "67765beb8b7940eac4ca2c55",
    postTitle: "Improve Posture with These Strength Routines",
    postContent: "Balanced nutrition fuels performance and promotes recovery.",
    tags: ["nutrition", "diet", "energy", "lifestyle", "balance"],
    createdAt: "Jun 10 2025 14:45:00",
    liked: ["testmember@gmail.com", "johnny.sins@example.com"],
    disliked: ["psazzadul1205@gmail.com"],
    comments: [
      {
        user: "Thomas King",
        role: "Trainer",
        userImg: "https://i.ibb.co.com/SwkPVWtN/cropped-image.jpg",
        time: "Jun 10 2025 15:15:00",
        content: "This is a helpful post about balance.",
        liked: ["user@gmail.com"],
        disliked: [],
      },
      {
        user: "Farzad sami",
        role: "Member",
        userImg: "https://i.ibb.co/8LH7MRm1/blob.jpg",
        time: "Jun 10 2025 15:15:00",
        content: "This is a helpful post about balance.",
        liked: [],
        disliked: ["johnny.sins@example.com"],
      },
      {
        user: "Muntaha",
        role: "Member",
        userImg: "https://i.ibb.co.com/gLgKcvwv/blob.jpg",
        time: "Jun 10 2025 15:15:00",
        content: "This is a helpful post about balance.",
        liked: [],
        disliked: [],
      },
    ],
  },
];
